import type { Quiz } from '@/types'

// ─── Seed data ─────────────────────────────────────────────────────────────────

const quizzes: Quiz[] = [
  // ── 1. Agent Fundamentals (from provided JSON) ──────────────────────────────
  {
    id: 'agent-fundamentals',
    title: 'Agent Fundamentals',
    description: 'Test your knowledge of AI agent design and implementation',
    category: 'agent-fundamentals',
    questions: [
      {
        id: 1,
        question: 'What is the primary purpose of an AI agent?',
        options: [
          'To replace human workers',
          'To autonomously perform tasks and make decisions',
          'To store large amounts of data',
          'To create visual interfaces',
        ],
        correctAnswer: 1,
        explanation:
          'AI agents are designed to autonomously perform tasks and make decisions based on their environment and goals.',
      },
      {
        id: 2,
        question: 'Which component is essential for an AI agent to learn from experience?',
        options: [
          'A graphical user interface',
          'A feedback mechanism',
          'A database connection',
          'A payment processor',
        ],
        correctAnswer: 1,
        explanation:
          'A feedback mechanism allows agents to learn from their actions and improve over time.',
      },
      {
        id: 3,
        question: "What is 'context window' in relation to AI models?",
        options: [
          'The browser window where AI runs',
          'The maximum amount of text a model can process at once',
          'The time period for model training',
          'The user interface for model configuration',
        ],
        correctAnswer: 1,
        explanation:
          'The context window defines how much information an AI model can consider in a single interaction.',
      },
      {
        id: 4,
        question: 'Which strategy helps manage limited context windows?',
        options: [
          'Adding more servers',
          'Using larger fonts',
          'Summarization and chunking',
          'Increasing screen resolution',
        ],
        correctAnswer: 2,
        explanation: 'Summarization and chunking help fit relevant information within context limits.',
      },
      {
        id: 5,
        question: "What is 'prompt engineering'?",
        options: [
          'Building physical AI hardware',
          'Designing effective instructions for AI models',
          'Creating user interfaces',
          'Managing cloud infrastructure',
        ],
        correctAnswer: 1,
        explanation:
          'Prompt engineering is the practice of designing and optimizing inputs to get desired outputs from AI models.',
      },
    ],
  },

  // ── 2. Prompt Engineering ────────────────────────────────────────────────────
  {
    id: 'prompt-engineering',
    title: 'Prompt Engineering',
    description: 'Master the art of crafting effective prompts for large language models',
    category: 'prompt-engineering',
    questions: [
      {
        id: 1,
        question: 'Which prompting technique asks the model to reason step-by-step before answering?',
        options: [
          'Zero-shot prompting',
          'Few-shot prompting',
          'Chain-of-thought prompting',
          'Retrieval-augmented generation',
        ],
        correctAnswer: 2,
        explanation:
          'Chain-of-thought (CoT) prompting instructs the model to show its reasoning steps, which significantly improves accuracy on complex tasks.',
      },
      {
        id: 2,
        question: 'What does "few-shot prompting" mean?',
        options: [
          'Using a very short system prompt',
          'Providing example input-output pairs inside the prompt',
          'Running the model with reduced compute',
          'Limiting the number of tokens in the response',
        ],
        correctAnswer: 1,
        explanation:
          'Few-shot prompting includes a small number of worked examples in the prompt so the model can infer the desired pattern or format.',
      },
      {
        id: 3,
        question: 'What is the role of a "system prompt" in chat-based LLMs?',
        options: [
          'To set the operating system language',
          'To define the model version to use',
          'To provide persistent instructions and persona to the model',
          'To cache previous conversations',
        ],
        correctAnswer: 2,
        explanation:
          'The system prompt is sent before the conversation begins and establishes the model\'s behavior, tone, and constraints for the entire session.',
      },
      {
        id: 4,
        question: 'What is "temperature" in the context of LLM generation?',
        options: [
          'The physical heat generated by GPU computation',
          'A parameter controlling the randomness of model outputs',
          'The number of tokens generated per second',
          'A measure of training data quality',
        ],
        correctAnswer: 1,
        explanation:
          'Temperature scales the probability distribution over tokens before sampling. Higher values (e.g., 1.0+) increase randomness; lower values (e.g., 0.2) make outputs more deterministic.',
      },
      {
        id: 5,
        question: 'Which technique mitigates hallucination by grounding the model in retrieved documents?',
        options: [
          'Prompt chaining',
          'Retrieval-Augmented Generation (RAG)',
          'Self-consistency sampling',
          'Instruction tuning',
        ],
        correctAnswer: 1,
        explanation:
          'RAG retrieves relevant documents at inference time and injects them into the prompt, giving the model factual context and reducing invented answers.',
      },
    ],
  },

  // ── 3. Model Selection ───────────────────────────────────────────────────────
  {
    id: 'model-selection',
    title: 'Model Selection',
    description: 'Learn how to choose the right AI model for different tasks and constraints',
    category: 'model-selection',
    questions: [
      {
        id: 1,
        question:
          'When low latency is critical and the task is straightforward, which model tier is most appropriate?',
        options: [
          'The largest frontier model available',
          'A small, fast model optimized for inference speed',
          'A multimodal model with vision capabilities',
          'A model fine-tuned for code generation only',
        ],
        correctAnswer: 1,
        explanation:
          'Smaller models trade raw capability for speed and cost. For simple, latency-sensitive tasks they are often the right choice over large frontier models.',
      },
      {
        id: 2,
        question: "What does a model's 'parameter count' primarily indicate?",
        options: [
          'The number of training examples seen',
          'The number of output tokens per second',
          'The size and complexity of the model, which correlates with capability and cost',
          'The number of supported languages',
        ],
        correctAnswer: 2,
        explanation:
          'Parameter count reflects how many learnable weights the model has. More parameters generally mean greater capability but also higher compute cost and latency.',
      },
      {
        id: 3,
        question: 'Fine-tuning a base model is most justified when:',
        options: [
          'You want the cheapest possible API calls',
          'The task requires consistent style or domain-specific vocabulary not achievable through prompting alone',
          'You need the model to browse the internet',
          'You want to use the model without an API key',
        ],
        correctAnswer: 1,
        explanation:
          'Fine-tuning is worth the overhead when a specialized task (e.g., medical coding, legal drafting) requires consistent behavior that prompt engineering alone cannot reliably achieve.',
      },
      {
        id: 4,
        question: 'Which capability distinguishes a "multimodal" model from a text-only model?',
        options: [
          'It can run on mobile devices',
          'It can process and generate multiple types of data such as images and audio alongside text',
          'It supports multiple programming languages',
          'It can call external APIs automatically',
        ],
        correctAnswer: 1,
        explanation:
          'Multimodal models accept inputs beyond text (e.g., images, audio, video) and can reason across modalities, enabling tasks like visual question answering.',
      },
      {
        id: 5,
        question: 'What is the primary advantage of running an open-weight model locally via Ollama?',
        options: [
          'It always outperforms closed-source frontier models',
          'It eliminates data privacy concerns and API costs by keeping inference on-device',
          'It requires no hardware resources',
          'It automatically selects the best prompt strategy',
        ],
        correctAnswer: 1,
        explanation:
          'Running open-weight models locally keeps all data on your machine, removing privacy risks associated with sending data to third-party APIs, while also eliminating per-token costs.',
      },
    ],
  },
]

// ─── Simulated network delay ───────────────────────────────────────────────────

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

// ─── Public API ────────────────────────────────────────────────────────────────

/**
 * Returns all available quizzes.
 * Simulates ~150 ms network latency.
 */
export async function fetchQuizzes(): Promise<Quiz[]> {
  await delay(150)
  return quizzes
}

/**
 * Returns a single quiz by id, or null if not found.
 * Simulates ~100 ms network latency.
 */
export async function fetchQuizById(id: string): Promise<Quiz | null> {
  await delay(100)
  return quizzes.find((q) => q.id === id) ?? null
}
